apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: acs-sensors-hub-info
  namespace: rhacm-hub
spec:
  clusterSelector:
    matchLabels:
      name: local-cluster