apiVersion: v1
kind: Namespace
metadata:
  name: stackrox
---
apiVersion: v1
kind: Namespace
metadata:
  name: rhacs-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: rhacs-operator-group
  namespace: rhacs-operator
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhacs-operator
  namespace: rhacs-operator
spec:
  channel: stable
  installPlanApproval: Automatic
  name: rhacs-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: v1
data: '{{hub copySecretData "policies" "admission-control-tls" hub}}'
kind: Secret
metadata:
  name: admission-control-tls
  namespace: stackrox
type: Opaque
---
apiVersion: v1
data: '{{hub copySecretData "policies" "collector-tls" hub}}'
kind: Secret
metadata:
  name: collector-tls
  namespace: stackrox
type: Opaque
---
apiVersion: v1
data: '{{hub copySecretData "policies" "sensor-tls" hub}}'
kind: Secret
metadata:
  name: sensor-tls
  namespace: stackrox
type: Opaque
---
apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  namespace: stackrox
  name: stackrox-secured-cluster-services
spec:
  clusterName: '{{hub .ManagedClusterName hub}}'
  auditLogs:
    collection: Auto
  centralEndpoint: '{{hub fromConfigMap "" "acs-config" "acs-host" hub}}'
  admissionControl:
    listenOnCreates: false
    listenOnEvents: true
    listenOnUpdates: false
  perNode:
    collector:
      collection: EBPF
      imageFlavor: Regular
    taintToleration: TolerateTaints
---
apiVersion: policy.open-cluster-management.io/v1
kind: CertificatePolicy
metadata:
  name: acs-bundle-certificates
spec:
  namespaceSelector:
    include: ["rhacm-hub"]
  remediationAction: inform
  severity: high
  minimumDuration: 720h
---
apiVersion: v1
data: '{{ copySecretData "stackrox" "admission-control-tls" }}'
kind: Secret
metadata:
  labels:
    certificate_key_name: admission-control-cert.pem
  name: admission-control-tls
  namespace: rhacm-hub
type: Opaque
---
apiVersion: v1
data: '{{ copySecretData "stackrox" "collector-tls" }}'
kind: Secret
metadata:
  labels:
    certificate_key_name: collector-cert.pem
  name: collector-tls
  namespace: rhacm-hub
type: Opaque
---
apiVersion: v1
data: '{{ copySecretData "stackrox" "sensor-tls" }}'
kind: Secret
metadata:
  labels:
    certificate_key_name: sensor-cert.pem
  name: sensor-tls
  namespace: rhacm-hub
type: Opaque
---
apiVersion: v1
data:
  acs-host: '{{ (lookup "route.openshift.io/v1" "Route" "stackrox" "central").spec.host }}:443'
kind: ConfigMap
metadata:
  name: acs-config
  namespace: rhacm-hub
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor
  namespace: stackrox
status:
  conditions:
    - status: "True"
      type: Available
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: collector
  namespace: stackrox
status:
  numberMisscheduled: 0