apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: advanced-cluster-security-operator
  namespace: openshift-operators
  annotations:
    policy.open-cluster-management.io/categories: ""
    policy.open-cluster-management.io/standards: ""
    policy.open-cluster-management.io/controls: ""
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1beta1
        kind: OperatorPolicy
        metadata:
          name: install-operator
        spec:
          remediationAction: enforce
          severity: critical
          complianceType: musthave
          subscription:
            name: rhacs-operator
            namespace: rhacs-operator
            channel: stable
            source: redhat-operators
            sourceNamespace: openshift-marketplace
            startingCSV: rhacs-operator.v4.6.2
          upgradeApproval: Automatic
          versions:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: advanced-cluster-security-central
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: platform.stackrox.io/v1alpha1
                kind: Central
                metadata:
                  name: stackrox-central-services
                  namespace: stackrox
                spec:
                  central:
                    exposure:
                      loadBalancer:
                        enabled: false
                        port: 443
                      nodePort:
                        enabled: false
                      route:
                        enabled: true
                    persistence:
                      persistentVolumeClaim:
                        claimName: stackrox-db
                  egress:
                    connectivityPolicy: Online
                  scanner:
                    analyzer:
                      scaling:
                        autoScaling: Enabled
                        maxReplicas: 5
                        minReplicas: 2
                        replicas: 3
                    scannerComponent: Enabled
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: advanced-cluster-security-operator-placement
  namespace: openshift-operators
spec:
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
  clusterSets:
    - hub-cluster
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: env
              operator: In
              values:
                - hub
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: advanced-cluster-security-operator-placement
  namespace: openshift-operators
placementRef:
  name: advanced-cluster-security-operator-placement
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: advanced-cluster-security-operator
    apiGroup: policy.open-cluster-management.io
    kind: Policy
