apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: advanced-cluster-security-operator-placement
  namespace: openshift-operators
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: hub-cluster
        operator: In
        values:
          - "true"
