apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-advanced-managed-cluster-security
  namespace: stackrox
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: managed-cluster-security-ns
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: stackrox
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: rhacs-operator
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: rhacs-operator-group
                  namespace: rhacs-operator
                spec: {}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: managed-cluster-security-operator-sub
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: rhacs-operator
                  namespace: rhacs-operator
                spec:
                  name: rhacs-operator
                  channel: latest
                  installPlanApproval: Automatic
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: managed-cluster-security-endpoints
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: platform.stackrox.io/v1alpha1
                kind: SecuredCluster
                metadata:
                  name: stackrox-secured-cluster-services
                  namespace: stackrox
                spec:
                  clusterName: >
                    {{ fromSecret "open-cluster-management-agent"
                    "hub-kubeconfig-secret" "cluster-name" | base64dec }}
                  auditLogs:
                    collection: Auto
                  centralEndpoint: >
                    {{ fromSecret "stackrox" "sensor-tls" "acs-host" | base64dec
                    }}
                  admissionControl:
                    listenOnCreates: false
                    listenOnEvents: true
                    listenOnUpdates: false
                  perNode:
                    collector:
                      collection: EBPF
                      imageFlavor: Regular
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: policy-advanced-managed-cluster-security-placement
  namespace: stackrox
spec:
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
  clusterSets:
    - hub-cluster
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: env
              operator: In
              values:
                - hub
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: policy-advanced-managed-cluster-security-placement
  namespace: stackrox
placementRef:
  name: policy-advanced-managed-cluster-security-placement
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: policy-advanced-managed-cluster-security
    apiGroup: policy.open-cluster-management.io
    kind: Policy
